# Alembic migration script for the database schema of the MENO platform.
"""knowledge_intelligence_schema

Revision ID: 332a4d6876d7
Revises: 
Create Date: 2026-06-21 15:41:08.765803

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector

# revision identifiers, used by Alembic.
revision: str = '332a4d6876d7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('behavioral_profiles',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('preferred_language', sa.String(), nullable=True),
    sa.Column('tone', sa.String(), nullable=True),
    sa.Column('context_size', sa.Integer(), server_default=sa.text('10'), nullable=False),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('knowledge_context',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('context_type', sa.String(), nullable=False),
    sa.Column('context_id', sa.String(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'context_type', 'context_id', name='uq_context_tenant_type_id')
    )
    op.create_table('knowledge_objects',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True),
    sa.Column('source_type', sa.String(), nullable=True),
    sa.Column('source_id', sa.String(), nullable=True),
    sa.Column('source_context', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_accessed', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('access_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('confidence', sa.Float(), server_default=sa.text('0.5'), nullable=False),
    sa.Column('importance', sa.Float(), server_default=sa.text('0.5'), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('tags', postgresql.ARRAY(sa.Text()), server_default=sa.text("'{}'"), nullable=False),
    sa.CheckConstraint("type IN ('memory', 'code_pattern', 'decision', 'api_spec', 'bug_report', 'refactoring', 'architecture')", name='check_knowledge_type'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_knowledge_objects_embedding', 'knowledge_objects', ['embedding'], unique=False, postgresql_using='ivfflat', postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_index('idx_ko_source_type_id', 'knowledge_objects', ['source_type', 'source_id'], unique=False)
    op.create_index('idx_ko_tags_gin', 'knowledge_objects', ['tags'], unique=False, postgresql_using='gin')
    op.create_index('idx_ko_tenant_user_type', 'knowledge_objects', ['tenant_id', 'user_id', 'type'], unique=False)
    op.create_index(op.f('ix_knowledge_objects_tenant_id'), 'knowledge_objects', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_knowledge_objects_user_id'), 'knowledge_objects', ['user_id'], unique=False)
    op.create_table('sessions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_activity', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('promoted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('promoted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'"), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessions_user_id'), 'sessions', ['user_id'], unique=False)
    op.create_table('knowledge_in_context',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('knowledge_object_id', sa.UUID(), nullable=False),
    sa.Column('context_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['context_id'], ['knowledge_context.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['knowledge_object_id'], ['knowledge_objects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('knowledge_object_id', 'context_id', name='uq_ko_in_context')
    )
    op.create_index(op.f('ix_knowledge_in_context_context_id'), 'knowledge_in_context', ['context_id'], unique=False)
    op.create_table('knowledge_relationships',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=True),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('target_id', sa.UUID(), nullable=False),
    sa.Column('relationship_type', sa.String(), nullable=False),
    sa.Column('confidence', sa.Float(), server_default=sa.text('0.5'), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('inferred', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.CheckConstraint("relationship_type IN ('supersedes', 'implements', 'depends_on', 'related_to', 'contradicts', 'extends', 'is_instance_of', 'mentioned_in')", name='check_relationship_type'),
    sa.CheckConstraint('source_id != target_id', name='check_no_self_loops'),
    sa.ForeignKeyConstraint(['source_id'], ['knowledge_objects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_id'], ['knowledge_objects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_rel_tenant_type', 'knowledge_relationships', ['tenant_id', 'relationship_type'], unique=False)
    op.create_index(op.f('ix_knowledge_relationships_source_id'), 'knowledge_relationships', ['source_id'], unique=False)
    op.create_index(op.f('ix_knowledge_relationships_target_id'), 'knowledge_relationships', ['target_id'], unique=False)
    op.create_table('session_messages',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'"), nullable=False),
    sa.CheckConstraint("role IN ('user', 'assistant', 'system')", name='check_session_message_role'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_session_messages_session_id'), 'session_messages', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_session_messages_session_id'), table_name='session_messages')
    op.drop_table('session_messages')
    op.drop_index(op.f('ix_knowledge_relationships_target_id'), table_name='knowledge_relationships')
    op.drop_index(op.f('ix_knowledge_relationships_source_id'), table_name='knowledge_relationships')
    op.drop_index('idx_rel_tenant_type', table_name='knowledge_relationships')
    op.drop_table('knowledge_relationships')
    op.drop_index(op.f('ix_knowledge_in_context_context_id'), table_name='knowledge_in_context')
    op.drop_table('knowledge_in_context')
    op.drop_index(op.f('ix_sessions_user_id'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_knowledge_objects_user_id'), table_name='knowledge_objects')
    op.drop_index(op.f('ix_knowledge_objects_tenant_id'), table_name='knowledge_objects')
    op.drop_index('idx_ko_tenant_user_type', table_name='knowledge_objects')
    op.drop_index('idx_ko_tags_gin', table_name='knowledge_objects', postgresql_using='gin')
    op.drop_index('idx_ko_source_type_id', table_name='knowledge_objects')
    op.drop_index('idx_knowledge_objects_embedding', table_name='knowledge_objects', postgresql_using='ivfflat', postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_table('knowledge_objects')
    op.drop_table('knowledge_context')
    op.drop_table('behavioral_profiles')
    # ### end Alembic commands ###
